
import type { Metadata } from "next";
import Topbar from "../components/home/Topbar";
import Sidenav from "../components/home/Sidenav";
import Recommend from "../components/home/Recommend";
import Mobilenav from "../components/home/Mobilenav";






export const metadata: Metadata = {
  title: "Intouch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
    <Topbar/>
    <Sidenav/>
        {children}
    {/* <Recommend/> */}
    <Mobilenav/>
    </div>
     
  );
}
