import type { Metadata } from "next";



export const metadata: Metadata = {
    title: "Intouch",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
     
         <div className="w-full h-screen bg-slate-100">
          {children}
         </div>
        
       
    );
  }